# Generated by Django 3.2.4 on 2021-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-11-22'),
            preserve_default=False,
        ),
    ]
